import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import { Layers, Plus, Trash2, Edit3, Database, LayoutGrid, FileText, ChevronRight, Calendar, Wand2, Sparkles, Loader2 } from 'lucide-react';
import toast from 'react-hot-toast';
import * as api from '../utils/api';
import InsightsFeed from '../components/InsightsFeed';

export default function SheetsListPage({ dataset, analysis }) {
  const navigate = useNavigate();
  const [tab, setTab] = useState('sheets');
  const [sheets, setSheets] = useState([]);
  const [dashboards, setDashboards] = useState([]);
  const [loading, setLoading] = useState(false);
  const [autoGenerating, setAutoGenerating] = useState(false);

  const load = async () => {
    setLoading(true);
    try {
      const [s, d] = await Promise.all([
        api.listSheets(dataset?.id),
        api.listDashboards(dataset?.id),
      ]);
      setSheets(s.sheets || []);
      setDashboards(d.dashboards || []);
    } catch { toast.error('Failed to load'); }
    finally { setLoading(false); }
  };

  useEffect(() => { load(); }, [dataset?.id]);

  const autoGenerate = async () => {
    if (!dataset?.id || autoGenerating) return;
    setAutoGenerating(true);
    try {
      const r = await api.autoGenerateDashboard(dataset.id);
      toast.success(`Generated dashboard with ${r.blueprintCount} charts`);
      navigate(`/dashboard/${r.dashboard.id}`);
    } catch (err) {
      toast.error(err.response?.data?.error || 'Auto-generate failed');
    } finally {
      setAutoGenerating(false);
    }
  };

  const handleDeleteSheet = async (id) => {
    if (!confirm('Delete this sheet? It will be removed from any dashboards using it.')) return;
    try { await api.deleteSheet(id); toast.success('Sheet deleted'); load(); } catch { toast.error('Delete failed'); }
  };
  const handleDeleteDashboard = async (id) => {
    if (!confirm('Delete this dashboard?')) return;
    try { await api.deleteDashboard(id); toast.success('Dashboard deleted'); load(); } catch { toast.error('Delete failed'); }
  };

  if (!dataset) return (
    <div className="max-w-2xl mx-auto px-6 pt-16 pb-16">
      <motion.div
        initial={{ opacity: 0, y: 8 }}
        animate={{ opacity: 1, y: 0 }}
        className="card p-8 text-center"
      >
        <div className="w-14 h-14 rounded-2xl bg-wiz-accent-soft border border-wiz-accent/20 flex items-center justify-center mx-auto mb-5">
          <Layers size={24} strokeWidth={1.5} className="text-wiz-accent" />
        </div>
        <p className="eyebrow mb-2">My Workbook</p>
        <h2 className="h3 mb-2">Your <span className="italic text-wiz-accent">saved sheets</span> will live here.</h2>
        <p className="text-sm text-wiz-text-secondary mb-6 max-w-md mx-auto leading-relaxed">
          Build a chart in the Sheet Builder, save it, and it shows up here. Group sheets into custom dashboards. Upload a dataset to get started.
        </p>
        <button onClick={() => navigate('/')} className="btn-primary">
          <Database size={14} strokeWidth={1.75} />
          Upload a dataset
        </button>
      </motion.div>
    </div>
  );

  return (
    <div className="max-w-6xl mx-auto px-6 py-8">
      <motion.div initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }} className="flex items-start justify-between mb-6 gap-3 flex-wrap">
        <div>
          <h2 className="text-xl font-extrabold font-display text-wiz-text mb-1 flex items-center gap-2">
            <Layers size={20} className="text-wiz-accent" />My Workbook
          </h2>
          <p className="text-sm text-wiz-muted font-body">Saved sheets and custom dashboards for <span className="text-wiz-text font-mono">{dataset.fileName}</span></p>
        </div>
        <div className="flex items-center gap-2">
          <motion.button onClick={autoGenerate} disabled={autoGenerating}
            whileHover={{ scale: autoGenerating ? 1 : 1.04 }} whileTap={{ scale: 0.96 }}
            className="flex items-center gap-1.5 px-3 py-2 rounded-xl bg-gradient-to-r from-wiz-violet/30 to-wiz-accent/30 border border-wiz-accent/40 text-wiz-text text-[11px] font-semibold transition-all btn-press disabled:opacity-50">
            {autoGenerating ? <Loader2 size={13} className="animate-spin" /> : <Wand2 size={13} />}
            {autoGenerating ? 'Generating...' : 'Auto-Dashboard'}
          </motion.button>
          <motion.button onClick={() => navigate('/sheet/new')} whileHover={{ scale: 1.04 }} whileTap={{ scale: 0.96 }}
            className="flex items-center gap-1.5 px-3 py-2 rounded-xl glass text-wiz-muted hover:text-wiz-accent hover:border-wiz-accent/30 text-[11px] font-semibold transition-all btn-press">
            <Plus size={13} />New Sheet
          </motion.button>
          <motion.button onClick={() => navigate('/composer/new')} whileHover={{ scale: 1.04 }} whileTap={{ scale: 0.96 }}
            className="flex items-center gap-1.5 px-3 py-2 rounded-xl bg-gradient-to-r from-wiz-accent-deep to-wiz-accent text-white text-[11px] font-semibold shadow-lg shadow-wiz-accent/20 btn-press">
            <Plus size={13} />New Dashboard
          </motion.button>
        </div>
      </motion.div>

      {/* Insights Feed — proactively-discovered findings, ranked by interestingness */}
      <div className="mb-5">
        <InsightsFeed dataset={dataset} onSheetCreated={() => load()} compact />
      </div>

      {/* Tab switcher */}
      <div className="inline-flex items-center bg-wiz-bg/60 backdrop-blur-sm rounded-xl p-1 border border-wiz-border/50 gap-1 mb-5">
        {[
          { id: 'sheets', label: 'Sheets', icon: FileText, count: sheets.length },
          { id: 'dashboards', label: 'Dashboards', icon: LayoutGrid, count: dashboards.length },
        ].map(t => {
          const Icon = t.icon; const active = tab === t.id;
          return (
            <button key={t.id} onClick={() => setTab(t.id)}
              className={`relative flex items-center gap-1.5 px-4 py-1.5 rounded-lg text-[11px] font-semibold transition-all ${active ? 'bg-wiz-accent text-white' : 'text-wiz-muted hover:text-wiz-text'}`}>
              <Icon size={12} />{t.label} <span className="opacity-60">({t.count})</span>
            </button>
          );
        })}
      </div>

      {loading && <div className="flex justify-center py-16"><div className="spinner w-10 h-10" /></div>}

      {!loading && tab === 'sheets' && (
        sheets.length === 0 ? (
          <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="text-center py-16">
            <div className="w-20 h-20 rounded-3xl bg-wiz-accent/5 border border-wiz-accent/10 flex items-center justify-center mx-auto mb-5"><FileText size={32} className="text-wiz-accent/30" /></div>
            <p className="text-base font-display font-semibold text-wiz-muted mb-2">No sheets yet</p>
            <p className="text-xs text-wiz-dim mb-5 font-body">Build your first custom visualization with the Sheet Builder</p>
            <motion.button onClick={() => navigate('/sheet/new')} whileHover={{ scale: 1.04 }} whileTap={{ scale: 0.96 }}
              className="inline-flex items-center gap-1.5 px-5 py-2.5 rounded-xl bg-gradient-to-r from-wiz-accent-deep to-wiz-accent text-white text-xs font-semibold btn-press">
              <Plus size={14} />Create First Sheet
            </motion.button>
          </motion.div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
            {sheets.map((s, i) => (
              <motion.div key={s.id} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.04 }}
                className="rounded-2xl bg-wiz-surface/40 border border-wiz-border/40 hover:border-wiz-accent/30 transition-all card-lift overflow-hidden group">
                <button onClick={() => navigate(`/sheet/${s.id}`)} className="w-full text-left">
                  <div className="aspect-video bg-gradient-to-br from-wiz-accent/10 to-wiz-emerald/5 border-b border-wiz-border/30 flex items-center justify-center">
                    <div className="text-center">
                      <span className="px-2 py-0.5 rounded-md text-[10px] font-mono font-bold bg-wiz-accent/20 text-wiz-accent-light uppercase">{s.spec?.chartType?.replace('_', ' ') || 'sheet'}</span>
                    </div>
                  </div>
                  <div className="p-3">
                    <h4 className="text-sm font-bold font-display text-wiz-text truncate">{s.name}</h4>
                    <p className="text-[10px] font-mono text-wiz-dim mt-0.5 flex items-center gap-1.5">
                      <Calendar size={9} />{new Date(s.updatedAt).toLocaleDateString()}
                    </p>
                  </div>
                </button>
                <div className="px-3 pb-3 flex items-center gap-1.5">
                  <button onClick={() => navigate(`/sheet/${s.id}`)} className="flex-1 flex items-center justify-center gap-1 px-2 py-1.5 rounded-lg bg-wiz-bg/40 hover:bg-wiz-accent/10 text-[10px] text-wiz-muted hover:text-wiz-accent-light font-semibold transition-all">
                    <Edit3 size={10} />Edit
                  </button>
                  <button onClick={() => handleDeleteSheet(s.id)} className="px-2 py-1.5 rounded-lg bg-wiz-bg/40 hover:bg-wiz-rose/10 text-wiz-dim hover:text-wiz-rose transition-all"><Trash2 size={10} /></button>
                </div>
              </motion.div>
            ))}
          </div>
        )
      )}

      {!loading && tab === 'dashboards' && (
        dashboards.length === 0 ? (
          <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="text-center py-16">
            <div className="w-20 h-20 rounded-3xl bg-wiz-emerald/5 border border-wiz-emerald/10 flex items-center justify-center mx-auto mb-5"><LayoutGrid size={32} className="text-wiz-emerald/30" /></div>
            <p className="text-base font-display font-semibold text-wiz-muted mb-2">No custom dashboards yet</p>
            <p className="text-xs text-wiz-dim mb-5 font-body">Save some sheets first, then arrange them into a dashboard</p>
            <motion.button onClick={() => navigate('/composer/new')} whileHover={{ scale: 1.04 }} whileTap={{ scale: 0.96 }}
              className="inline-flex items-center gap-1.5 px-5 py-2.5 rounded-xl bg-gradient-to-r from-wiz-emerald-deep to-wiz-emerald text-white text-xs font-semibold btn-press">
              <Plus size={14} />Create First Dashboard
            </motion.button>
          </motion.div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            {dashboards.map((d, i) => (
              <motion.div key={d.id} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.04 }}
                className="rounded-2xl bg-wiz-surface/40 border border-wiz-border/40 hover:border-wiz-emerald/30 transition-all card-lift overflow-hidden group">
                <button onClick={() => navigate(`/composer/${d.id}`)} className="w-full text-left p-4">
                  <div className="flex items-center justify-between mb-2">
                    <h4 className="text-sm font-bold font-display text-wiz-text">{d.name}</h4>
                    <ChevronRight size={14} className="text-wiz-muted" />
                  </div>
                  <div className="grid grid-cols-4 gap-1 mb-3 h-20">
                    {Array.from({ length: 4 }).map((_, j) => (
                      <div key={j} className={`rounded-md border border-wiz-border/30 ${j < (d.tiles?.length || 0) ? 'bg-wiz-emerald/15' : 'bg-wiz-bg/30'}`} />
                    ))}
                  </div>
                  <p className="text-[10px] font-mono text-wiz-dim flex items-center gap-1.5">
                    <LayoutGrid size={9} />{d.tiles?.length || 0} tiles · <Calendar size={9} />{new Date(d.updatedAt).toLocaleDateString()}
                  </p>
                </button>
                <div className="px-4 pb-3 flex items-center gap-1.5">
                  <button onClick={() => navigate(`/composer/${d.id}`)} className="flex-1 flex items-center justify-center gap-1 px-2 py-1.5 rounded-lg bg-wiz-bg/40 hover:bg-wiz-emerald/10 text-[10px] text-wiz-muted hover:text-wiz-emerald font-semibold transition-all">
                    <Edit3 size={10} />Open
                  </button>
                  <button onClick={() => handleDeleteDashboard(d.id)} className="px-2 py-1.5 rounded-lg bg-wiz-bg/40 hover:bg-wiz-rose/10 text-wiz-dim hover:text-wiz-rose transition-all"><Trash2 size={10} /></button>
                </div>
              </motion.div>
            ))}
          </div>
        )
      )}
    </div>
  );
}
