/**
 * Auto-visualization endpoints.
 *
 * POST /api/auto/dashboard/:datasetId
 *   Generate a complete dashboard from a dataset. Creates one sheet per
 *   chart (so users can edit them later) and a dashboard with tiled layout.
 *   Returns the new dashboard ID + the rendered tiles inline so the client
 *   doesn't need a second roundtrip.
 *
 * POST /api/auto/explore/:datasetId
 *   Run the interestingness scan and return ranked findings. Each finding
 *   has a chartSpec the client can use to open a focused exploration sheet.
 *
 * POST /api/auto/explore/:datasetId/save-finding
 *   Convert a finding into a saved sheet. The client passes the finding;
 *   we materialize it as a sheet with a descriptive name.
 */

const express = require('express');
const datasetStore = require('../utils/datasetStore');
const sheetStore = require('../utils/sheetStore');
const autoDashboard = require('../utils/autoDashboard');
const autoExplore = require('../utils/autoExplore');
const statInsights = require('../utils/statInsights');
const { buildChartFromSheet } = require('../utils/sheetSpecBuilder');
const { perUserRateLimit } = require('../middleware/perUserRateLimit');

const router = express.Router();

// Each of these endpoints can take 200–1500ms of CPU on a real dataset.
// Without per-user limits, one tenant running auto-explore in a tight loop
// can starve every other tenant of event-loop time.
// 6 burst, 6/min sustained — generous for real users, choking for runaway scripts.
const heavyLimit = perUserRateLimit({
  capacity: 6,
  refillPerSec: 6 / 60,
  name: 'heavy-analytics',
});

// ─── AUTO-DASHBOARD ──────────────────────────────────────────────────────────

router.post('/dashboard/:datasetId', heavyLimit, async (req, res) => {
  try {
    const ds = datasetStore.get(req.params.datasetId, req.user?.id);
    if (!ds) return res.status(404).json({ error: 'Dataset not found' });

    const blueprints = autoDashboard.generate({ analysis: ds.analysis });
    if (!blueprints.length) {
      return res.status(400).json({ error: 'Could not generate a dashboard — dataset needs at least one numeric column.' });
    }

    // For each blueprint: render the chart, attach a stat-driven insight,
    // save it as a sheet, and queue it as a dashboard tile.
    const tiles = [];
    const renderedTiles = [];      // returned to client so it can render immediately

    for (let i = 0; i < blueprints.length; i++) {
      const bp = blueprints[i];

      // Render the chart so we can derive an insight from real data
      let chartResult;
      try {
        chartResult = buildChartFromSheet(bp.spec, ds);
      } catch (err) {
        // Skip charts that fail to render — better to ship 4 working charts
        // than 6 with two errors.
        console.warn(`[auto-dashboard] Skipping ${bp.name}: ${err.message}`);
        continue;
      }
      if (!chartResult.chartData || (Array.isArray(chartResult.chartData) && !chartResult.chartData.length)) {
        continue;     // empty chart
      }

      // Build the insight using statInsights with the right keys for this focus
      const insight = buildInsight(bp, chartResult, ds.analysis);

      // Save the chart as a sheet so the user can open and edit it
      const savedSheet = sheetStore.createSheet({
        name: bp.name,
        datasetId: ds.id,
        datasetName: ds.fileName,
        spec: bp.spec,
        ownerId: req.user?.id,
      });

      // Tile placement — simple 2-column grid
      const col = i % 2;
      const row = Math.floor(i / 2);
      const tile = {
        id: `tile_${Date.now()}_${i}`,
        sheetId: savedSheet.id,
        x: col * 6,           // 12-col grid; each tile is 6 wide
        y: row * 4,           // each tile is 4 high
        w: bp.layout?.w === 1 ? 4 : 6,
        h: bp.layout?.h === 1 ? 3 : 4,
        insight,              // attach insight directly to the tile
      };
      tiles.push(tile);

      renderedTiles.push({
        ...tile,
        sheet: savedSheet,
        chartSpec: chartResult.spec,
        chartData: chartResult.chartData,
        stackKeys: chartResult.stackKeys,
      });
    }

    if (!tiles.length) {
      return res.status(400).json({ error: 'Generated all charts but none rendered successfully.' });
    }

    // Save the dashboard
    const dashboard = sheetStore.createDashboard({
      name: `Auto Dashboard — ${ds.fileName}`,
      datasetId: ds.id,
      datasetName: ds.fileName,
      tiles,
      ownerId: req.user?.id,
      meta: { autoGenerated: true, generatedAt: Date.now() },
    });

    res.json({
      dashboard,
      tiles: renderedTiles,
      poweredBy: 'heuristic',
    });
  } catch (err) {
    console.error('[auto-dashboard] error:', err);
    res.status(500).json({ error: err.message });
  }
});

/**
 * Given a chart blueprint and its rendered output, produce a one-sentence
 * insight via statInsights. Maps each blueprint's `insightFocus` to the
 * right statInsights call with the right keys.
 */
function buildInsight(blueprint, chartResult, analysis) {
  const focus = blueprint.insightFocus;
  const data = chartResult.chartData;
  const cols = blueprint.spec.columns || [];
  const rows = blueprint.spec.rows || [];
  const dim = cols[0]?.name || rows.find(r => r.type !== 'numeric')?.name;
  const meas = rows.find(r => r.type === 'numeric')?.name || cols.find(c => c.type === 'numeric')?.name;
  const date = cols.find(c => c.type === 'date')?.name || rows.find(r => r.type === 'date')?.name;

  const columnStats = analysis?.columns?.find(c => c.name === meas)?.stats;

  const keys = {
    kpi: { dimKey: dim, valueKey: meas },
    trend: { dateKey: date, valueKey: meas },
    distribution: { dimKey: dim, valueKey: meas },
    concentration: { dimKey: dim, valueKey: meas },
    spread: { valueKey: meas, columnStats },
    correlation: { xKey: cols[0]?.name, yKey: rows[0]?.name },
    share: { dimKey: dim, valueKey: meas },
  }[focus] || { dimKey: dim, valueKey: meas };

  try {
    return statInsights.forChart({ chartData: data, focus, keys, columnStats });
  } catch (err) {
    return null;
  }
}

// ─── AUTO-EXPLORE ────────────────────────────────────────────────────────────

router.post('/explore/:datasetId', heavyLimit, async (req, res) => {
  try {
    const ds = datasetStore.get(req.params.datasetId, req.user?.id);
    if (!ds) return res.status(404).json({ error: 'Dataset not found' });

    const maxFindings = parseInt(req.body?.maxFindings) || 12;
    const result = autoExplore.explore(ds, { maxFindings });

    res.json({
      ...result,
      poweredBy: 'heuristic',
    });
  } catch (err) {
    console.error('[auto-explore] error:', err);
    res.status(500).json({ error: err.message });
  }
});

router.post('/explore/:datasetId/save-finding', (req, res) => {
  try {
    const { finding } = req.body;
    if (!finding?.chartSpec) return res.status(400).json({ error: 'finding.chartSpec required' });

    const ds = datasetStore.get(req.params.datasetId, req.user?.id);
    if (!ds) return res.status(404).json({ error: 'Dataset not found' });

    // Sanity-check that the chart spec renders
    let chartResult;
    try {
      chartResult = buildChartFromSheet(finding.chartSpec, ds);
    } catch (err) {
      return res.status(400).json({ error: 'Finding chart failed to render: ' + err.message });
    }

    const sheet = sheetStore.createSheet({
      name: finding.title || 'Finding',
      datasetId: ds.id,
      datasetName: ds.fileName,
      spec: finding.chartSpec,
      ownerId: req.user?.id,
      meta: { fromFinding: finding.type, severity: finding.severity },
    });

    res.json({ sheet, chartSpec: chartResult.spec, chartData: chartResult.chartData });
  } catch (err) {
    console.error('[save-finding] error:', err);
    res.status(500).json({ error: err.message });
  }
});

// ─── KEY DRIVER ANALYSIS ─────────────────────────────────────────────────────

router.post('/drivers/:datasetId', heavyLimit, async (req, res) => {
  try {
    const ds = datasetStore.get(req.params.datasetId, req.user?.id);
    if (!ds) return res.status(404).json({ error: 'Dataset not found' });

    const { target, maxDrivers } = req.body || {};
    if (!target) return res.status(400).json({ error: 'target column name required' });

    const driverEngine = require('../utils/keyDriverAnalysis');
    const result = driverEngine.analyzeDrivers(ds, target, { maxDrivers: maxDrivers || 8 });

    res.json({ ...result, poweredBy: 'heuristic' });
  } catch (err) {
    console.error('[drivers] error:', err);
    res.status(500).json({ error: err.message });
  }
});

// ─── DECOMPOSITION TREE ──────────────────────────────────────────────────────
// Three endpoints. Each takes the dataset id + a path of (dim, value) pairs
// representing where you currently are in the tree. The path is sent fresh
// from the client on every request — the server does not persist tree state.
// This keeps the server stateless and lets multiple users explore the same
// dashboard independently.

const decompTree = require('../utils/decompositionTree');

router.post('/decomp/:datasetId/root', heavyLimit, (req, res) => {
  try {
    const ds = datasetStore.get(req.params.datasetId, req.user?.id);
    if (!ds) return res.status(404).json({ error: 'Dataset not found' });

    const { measure, agg = 'sum', path = [] } = req.body || {};
    if (!measure) return res.status(400).json({ error: 'measure is required' });

    const root = decompTree.getRoot(ds, measure, agg, path);
    const suggestions = decompTree.suggestNextDim(ds, {
      path, measure, agg, columns: ds.analysis?.columns,
    });
    res.json({ root, suggestions });
  } catch (err) {
    console.error('[decomp/root] error:', err);
    res.status(400).json({ error: err.message });
  }
});

router.post('/decomp/:datasetId/expand', heavyLimit, (req, res) => {
  try {
    const ds = datasetStore.get(req.params.datasetId, req.user?.id);
    if (!ds) return res.status(404).json({ error: 'Dataset not found' });

    const { path = [], dimension, measure, agg = 'sum', maxChildren = 10 } = req.body || {};
    const result = decompTree.expand(ds, { path, dimension, measure, agg, maxChildren });
    // Also compute suggestions for the children, so the UI can pre-show
    // hints under each child without an extra round-trip.
    const childSuggestions = {};
    for (const c of result.children) {
      childSuggestions[c.value] = decompTree.suggestNextDim(ds, {
        path: c.path, measure, agg, columns: ds.analysis?.columns,
      }).slice(0, 3);   // top 3 for each child
    }
    res.json({ ...result, childSuggestions });
  } catch (err) {
    console.error('[decomp/expand] error:', err);
    res.status(400).json({ error: err.message });
  }
});

module.exports = router;
